declare module 'npm-kit-tab'
declare module 'npm-kit-toggle'
declare module '@qpokychuk/ripple'
declare module '@fancyapps/ui'
declare module '@fancyapps/ui/src/Fancybox/l10n/ru'
declare module 'ymaps'
